--- #YAML:1.0
name:               Amazon-Agent
version:            0.01
abstract:           A generic Amazon Web Services (AWS) user agent for making and receiving requests. 
author:
    - Timothy Appnel <tima@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::ErrorHandler:  0
    Data::Dumper:         0
    Digest::HMAC_SHA1:    0
    Exporter:             0
    HTTP::Date:           0
    HTTP::Request:        0
    HTTP::Response:       0
    LWP::UserAgent:       0
    MIME::Base64:         0
    perl:                 5.006
    XML::Simple:          2
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/tima/perl-amazon-agent
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
